language: python
python:
  -"3.6"
virtualenv:
  system_site_packages: true

services:
  -docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
